collator/src/mempool/impls/std_impl.rs
consensus/src/engine/input_buffer.rs

make connfig values more noticeable

fix(consensus): missprint in input buffer

---

Cargo.lock
Cargo.toml
cli/src/cmd/node/control.rs
control/src/client.rs
control/src/proto.rs
control/src/server.rs

Example output:
```json
{
"init_mc_seqno": 0,
"init_mc_block_id": "-1:8000000000000000:0:d5c923593e3ac9370830b9508d2cb97c402a185501b554532f2c2f8a011c6838:e0e28028d98c836dfec589a2f8a50401bf06fe10ed8d957a3a6b1549e420c504",
"latest_mc_seqno": 39,
"latest_mc_block_id": "-1:8000000000000000:39:7f1b905b831b3d9b6eff05aaacd5f11a79c32afcadd87eb2d7a84f8700398331:47b22617e9c7a1b3dc57943cda2d48bcdb7f6e3f18cd0969f876ad710ab0db6e",
"time_diff": 4,
"is_synced": true,
"in_current_vset": true,
"in_next_vset": false,
"is_elected": true
}
```

feat(cli): add `tycho node status` cli command

---

consensus/src/effects/context.rs

regress of b634ed01 in 8f1c3323

fix(consensus): short validation span log

---

Cargo.lock
core/src/blockchain_rpc/client.rs
scripts/gen-dashboard.py
util/Cargo.toml
util/benches/p2.rs
util/src/lib.rs
util/src/time/mod.rs
util/src/time/p2.rs

```
p2_single_insert        time:   [17.227 ns 17.248 ns 17.270 ns]
Found 2 outliers among 100 measurements (2.00%)
1 (1.00%) high mild
1 (1.00%) high severe
p2_single_value_read    time:   [1.3073 ns 1.3074 ns 1.3075 ns]
Found 3 outliers among 100 measurements (3.00%)
2 (2.00%) high mild
1 (1.00%) high severe
p2_amortized_insert     time:   [5.0904 µs 5.0938 µs 5.0983 µs]
Found 31 outliers among 100 measurements (31.00%)
17 (17.00%) low severe
1 (1.00%) low mild
4 (4.00%) high mild
9 (9.00%) high severe
p2_insert_and_read      time:   [17.966 ns 17.984 ns 18.003 ns]
Found 8 outliers among 100 measurements (8.00%)
3 (3.00%) high mild
5 (5.00%) high severe
```

feat(util): implement P-Square algorithm for streaming percentile calcualtion

---

cli/src/cmd/init/mod.rs
cli/src/cmd/node/mod.rs
cli/src/node/config.rs

feat(cli): regenerate node keys on start if file does not exist

---

cli/src/cmd/node/control.rs
cli/src/node/mod.rs
control/src/client.rs
control/src/lib.rs
control/src/proto.rs
control/src/server.rs

refactor(control): merge node info with status response

---

consensus/src/intercom/dependency/downloader.rs

Fixed `not found` response count and removed `unreliable_peers` field as a source of error: the node cannot always determine that it lags too far from consensus and which peer must have point to return.   
Also fixed related metric and made `break None` logic a bit more explicit and readable.

fix(consensus): downloader hangup on deep sync

---

consensus/src/intercom/dependency/limiter.rs

will misbehave if tokio is overwhelmed with tasks anyway

fix(consensus): make `Limiter` order test a bit more reproducible

---

network/src/network/mod.rs

Previously, we assumed that `wmem_max` and `rmem_max` are accessible if procfs is available, but this is not always the case(hi WSL).

fix(network): check that both `wmem` and `rmem` exist before using them

---

storage/src/store/block/mod.rs

Improves compression ratio a bit, but might slow it down due to random reads. Needs a heck

feat(storage): group archive entries by entry type

---

network/src/lib.rs
network/src/overlay/background_tasks.rs
network/src/overlay/config.rs
network/src/overlay/mod.rs
network/src/overlay/public_overlay.rs
network/src/proto.tl
network/src/proto/overlay.rs

Alternative to https://github.com/broxus/tycho/pull/615

feat(network): collect public entries for peers from queries

---

collator/src/manager/mod.rs

This fixes the case when block was sent to sync from collator and was processed by state applier before state update was reported to mempool. In this race conditions top processed to anchor may be notified to mempool before the state update.

notify state update to mempool before sending block to sync

---

collator/src/mempool/impls/std_impl.rs
collator/src/mempool/impls/std_impl/state_update_queue.rs

relaxes requirements on collator events order

feature(collator): improve mempool state update queue

---

consensus/src/dag/dag_point_future.rs
consensus/src/effects/task.rs
consensus/src/engine/mempool_config.rs
consensus/src/test_utils/bootstrap.rs

https://github.com/broxus/tycho/pull/507#discussion_r2012152369

feature(consensus): limit spawn blocking

---

collator/src/collator/do_collate/finalize.rs

**TESTS**
**Unit Tests**
No changes
**Network Tests**
No special coverage
**Manual Tests**
Tested by 20k transfers (run-everwallets20). Time diff jumps removed. See screenshots below.
Expected impact
Collator should process messages normally when heavy load finished.
None
None
Collator. Work Units Calculation - fully compatible
We limit max accumulated wu to cover only 210 rounds. Under heavy load if some node is late (e.g. collating mb 100 when others collating mb 110) then it will produce mismatched mb 100 and then sync to the last one. All nodes in consensus will produce identical next blocks after restart.
Required
Better to perform update when no …

limit accumulated wu

---

collator/src/manager/mod.rs

None
None
fully compatible
Not Required
**TESTS**
**Unit Tests**
no coverage
**Network Tests**
no coverage
**Manual Tests**
Tested on devnet2
1. Enlarge elections period
```
/setzerostate .params.15 = {
"validators_elected_for": 1800,
"elections_start_before": 900,
"elections_end_before": 120,
"stake_held_for": 900
}
```
2. Disable elections participation
```
for i in {1..19}; do { OUTPUT=$(ssh tycho-devnet2-validator${i}.broxus "sudo systemctl stop tycho-elect 2>&1"); echo "VLD${i}: ${OUTPUT}"; }& done; wait
```
3. Set the minimal vset size = 3
```
./update-next-vset.sh 3 0 http://45.92.131.2:8080/rpc …
```

fix(collator): sync on key block anyway

---

collator/src/collator/do_collate/execute.rs
collator/src/collator/do_collate/mod.rs
collator/src/collator/messages_reader/mod.rs
collator/src/collator/types.rs
scripts/gen-dashboard.py

None
None
Not Required
---
---
No covarage
No covarage
- [1-255]
[30k tokens](https://grafana.broxus.com/d/cdlaji62a1b0gb/tycho-node-metrics-test?orgId=1&from=2025-06-12T13:06:43.193Z&to=2025-06-12T13:18:58.165Z&timezone=browser&var-source=ced0ihciqrn5sb&var-instance=tycho-devnet2-validator1&var-workchain=$__all&var-partition=$__all&var-kind=$__all&var-method=$__all&var-peer_id=$__all&var-remote_addr=$__all&refresh=10s)
---
**Notes/Additional Comments:**  
Internal queue length is calculating by cumulative statistics

feature(collator): queue len metrics by statistics. Closes #689

---

cli/src/cmd/debug/mempool.rs
collator/src/mempool/impls/std_impl.rs
collator/src/mempool/impls/std_impl/anchor_handler.rs
consensus/examples/engine.rs
consensus/src/dag/commit/mod.rs
consensus/src/dag/dag_point_future.rs
consensus/src/dag/dag_round.rs
consensus/src/dag/verifier.rs
consensus/src/effects/alt_format.rs
consensus/src/effects/mod.rs
consensus/src/engine/impl_.rs
consensus/src/engine/lifecycle/args.rs
consensus/src/engine/round_task.rs
consensus/src/intercom/broadcast/broadcast_filter.rs
consensus/src/intercom/core/responder.rs
consensus/src/intercom/dependency/uploader.rs
consensus/src/lib.rs
consensus/src/models/point_status.rs
consensus/src/storage/adapter_store.rs
consensus/src/storage/db.rs
consensus/src/storage/db_cleaner.rs
consensus/src/storage/mod.rs
consensus/src/storage/status_flags.rs
consensus/src/storage/store.rs
consensus/src/storage/tables.rs
consensus/src/test_utils/dag.rs

None
None
Full
Not Required
No coverage
No coverage
transfers-25k

refactor(consensus): db after storage split

---

consensus/src/dag/anchor_stage.rs
consensus/src/dag/dag_location.rs
consensus/src/dag/dag_point_future.rs
consensus/src/dag/dag_round.rs
consensus/src/dag/mod.rs
consensus/src/dag/verifier.rs
consensus/src/engine/committer_task.rs
consensus/src/engine/impl_.rs
consensus/src/engine/lifecycle/recover.rs
consensus/src/engine/mempool_config.rs
consensus/src/engine/round_task.rs
consensus/src/intercom/dependency/downloader.rs
consensus/src/models/cert.rs
consensus/src/models/point/data.rs
consensus/src/models/point/info.rs

None
None
Full
Not Required
No coverage
No coverage
local `just mempool`

mempool minor fixes and refactor

---

README.md
base.Dockerfile
simulator/README.md
simulator/src/backend/k3s_docker.rs
tycho.Dockerfile

None
None
---
Full
Not Required
---
---
No coverage
No coverage
Simulator builds and runs

fix(simulator): build with updated rocksdb

---

Cargo.lock
Cargo.toml
README.md
base.Dockerfile
simulator/README.md
simulator/src/backend/k3s_docker.rs
tycho.Dockerfile

No more build errors on GCC 15 and Clang 20 (until something breaks again :clown_face:)

chore: bump rocksdb version to 10.4.2

---

consensus/examples/engine.rs

[None]
[None]
---
Affected features:
[fully compatible]
[Not Required]
---
[No impact expected]
---
[No coverage]
[No coverage]
[Manual tests used]
---
**Notes/Additional Comments:**  
Resolve https://github.com/broxus/tycho/issues/830

feature(consensus): clean temp dir in example

---

consensus/src/intercom/dependency/downloader.rs

[None]
[None]
---
[fully compatible]
[Not Required]
---
[Expected impact]
Expect reducing amount of new requests when we have already downloading points.
[Covered by:]
- linear_basic
- linear_already_downloading
- exponential_basic
- exponential_already_downloading
[No coverage]
[Manual tests used]
---
**Notes/Additional Comments:**  
For resolving: https://github.com/broxus/tycho/issues/756

Reduce downloader's requests

---

core/src/storage/block/blobs/mod.rs
core/src/storage/persistent_state/mod.rs
core/src/storage/shard_state/mod.rs
rpc/src/state/storage.rs

None
None
---
Fully compatible
Not Required
---
---
No

fix(core): capture guards and permits by spawned tasks

---

cli/src/cmd/tools/bc.rs
docs/cli-reference.md

Allows updating config to experiment with params that are not yet "stabilized" without requiring patches to the node.

feat(cli): allow set/get config param as a raw cell

---

collator/src/manager/mod.rs
collator/src/types.rs

NODE CONFIGURATION MODEL CHANGES
[None]
BLOCKCHAIN CONFIGURATION MODEL CHANGES
[None]
COMPATIBILITY
[FULL]
SPECIAL DEPLOYMENT ACTIONS
[Not Required]
PERFORMANCE IMPACT
[No impact expected]
TESTS
Unit Tests
[No coverage]
Network Tests
[No coverage]
Manual Tests
[dex-1500
](https://grafana.broxus.com/d/cdlaji62a1b0gb/tycho-node-metrics?orgId=1&from=2025-09-15T10:37:54.057Z&to=2025-09-15T10:59:05.459Z&timezone=browser&var-source=ced0ihciqrn5sb&var-instance=tycho-devnet6-validator8&var-instance=tycho-devnet6-validator9&var-instance=tycho-devnet6-validator7&var-instance=tycho-devnet6-validator6&var-instance=tycho-devnet6-validator5&var-instance=tycho-devnet6-validator4&var-instance=tycho-devnet6-validator3&var-instance=tycho-devnet6-validator2&var-instance=tycho-devnet6-validator13&var-instance …

chore: enable support `CapOmitMasterBlockHistory` capability

---

collator/src/collator/mod.rs

[None]
[None]
---
[fully compatible]
[Not Required]
---
[No impact expected]
---
[No coverage]
[No coverage]

fix(collator): added missed apply merkle updates metrics

---

cli/src/cmd/node/control.rs
cli/src/cmd/tools/gen_dht.rs
cli/src/node/mod.rs
consensus/examples/engine.rs
consensus/src/test_utils/bootstrap.rs
control/src/client.rs
control/src/proto.rs
control/src/server.rs
core/src/block_strider/provider/blockchain_provider.rs
core/src/overlay_client/config.rs
core/src/overlay_client/mod.rs
core/src/overlay_client/neighbours.rs
docs/cli-reference.md
network/examples/network_node.rs
network/src/dht/mod.rs
network/src/overlay/mod.rs
network/src/types/peer_id.rs
scripts/gen-dashboard.py

None
None
---
Full compatibility
Not Required
---
---
No

Minor network fixes. Network tooling
