broxus/tycho

Cargo.lock
Cargo.toml
cli/src/cmd/tools/gen_zerostate.rs
collator/src/collator/mod.rs
collator/src/collator/mq_iterator_adapter.rs
docs/validator.md

Waiting when macros in `everscale-types` will be updated to support versioning. Then will update `CollationConfig` in types with backward compatibility and finish this feature.

feat(collator): collate empty shard block by timeout when no messages

---

Cargo.lock
Cargo.toml
storage/src/db/kv_db/mod.rs
storage/src/db/kv_db/tables.rs
storage/src/lib.rs
storage/src/store/block/mod.rs
storage/src/store/block/package_entry.rs
storage/src/store/block_connection/mod.rs
storage/src/store/block_handle/mod.rs
storage/src/store/shard_state/mod.rs

BREAKING: A new column family is required now - `full_block_ids`

feat(storage)!: reduce `remove_blocks` IO

---

collator/src/collator/mod.rs
collator/src/collator/tests/collator_tests.rs
collator/src/collator/types.rs

We didn't reset `has_externals` of initial anchors import on collator resume/init after sync. So i possibly can be `has_externals: true` after initial import when actually it is not true. Now we update flag according to actual our externals count after initial import.
Use `processed_to` anchor from prev block if it ahead of master to avoid incorrect block after sync.

fix(collator): update has_externals on initial anchors import

---

consensus/src/engine/mempool_config.rs
consensus/src/intercom/broadcast/broadcast_filter.rs
consensus/src/intercom/dependency/uploader.rs
consensus/src/test_utils/bootstrap.rs
storage/src/store/mempool/point_status.rs

* clause was inverted so cache dropped point bodies so dag had to download them
* `Uploader` responded that point does not exist (as final decision) if it had default status in storage during validation

fix(consensus): future rounds cache in `BroadcastFilter`

---

block-util/src/state/min_ref_mc_state.rs
block-util/src/state/shard_state_stuff.rs
cli/src/node/mod.rs
collator/src/test_utils.rs
collator/tests/adapter_tests.rs
collator/tests/collation_tests.rs
core/src/block_strider/mod.rs
core/src/block_strider/starter/cold_boot.rs
core/src/block_strider/state_applier.rs
core/tests/archives.rs
core/tests/utils/mod.rs
light-node/src/cli.rs
storage/src/store/persistent_state/tests.rs
storage/src/store/shard_state/mod.rs

We were using a couple of unrelated trackers which caused GC to delete states loaded from the storage despite having alive handles acquired by state applier.
Now we use a single instance of this tracker provided by `ShardStateStorage::min_ref_mc_state`.

fix: use a single instance of mc ref tracker for all parts of the node

---

block-util/src/queue/proto.rs
collator/src/collator/do_collate/finalize.rs
collator/src/internal_queue/state/commited_state.rs
collator/src/internal_queue/state/shard_iterator.rs
collator/src/internal_queue/state/state_iterator.rs
collator/src/internal_queue/state/uncommitted_state.rs
collator/tests/internal_queue.rs
scripts/gen-dashboard.py
storage/src/db/kv_db/tables.rs
storage/src/store/internal_queue/mod.rs

Reducing iterator init time 
master [test](https://grafana.broxus.com/d/cdlaji62a1b0gb/tycho-node-metrics?orgId=1&var-source=qG5wKEF4z&var-instance=tycho-devnet3-validator1&var-instance=tycho-devnet3-validator10&var-instance=tycho-devnet3-validator11&var-instance=tycho-devnet3-validator12&var-instance=tycho-devnet3-validator13&var-instance=tycho-devnet3-validator2&var-instance=tycho-devnet3-validator3&var-instance=tycho-devnet3-validator4&var-instance=tycho-devnet3-validator5&var-instance=tycho-devnet3-validator6&var-instance=tycho-devnet3-validator7&var-instance=tycho-devnet3-validator8&var-instance=tycho-devnet3-validator9&var-workchain=0&var-kind=All&var-method=All&from=1738054577086&to=1738055868806)
current branch same [test](https://grafana.broxus.com/d/cdlaji62a1b0gb/tycho-node-metr …

feature(collator): improve int queue performance

---

Cargo.lock
Cargo.toml

Adds these opcodes:
- `F802` — `BUYGAS (x – )`
- `F804` — `GRAMTOGAS (x – g)`
- `F805` — `GASTOGRAM (g – x)`
https://github.com/broxus/tycho-vm/commit/bcb9ff6b10d7b4a8df6a5add9408b3bb53e78f46

feat(collator): add more gasops to VM

---

collator/src/collator/do_collate/finalize.rs
collator/src/collator/do_collate/mod.rs
collator/src/collator/do_collate/prepare.rs
collator/src/collator/types.rs
collator/src/types.rs

`CollatorConfig.supported_block_version` and `CollatorConfig.supported_capabilities` are now set up only in code.
We need to remove `collator.supported_block_version` and `collator.supported_capabilities` from the node's `config.json`.

fix(collator): set gen_software to block from blockchain config

---

block-util/src/config/mod.rs
cli/src/cmd/elect/mod.rs
collator/src/collator/do_collate/mod.rs

On network with a high gas price the recovered fee threshold of 1 token is not enough to pay for execution. This PR applies a gas price factor to that threshold so there will always be enough to cover gas fee.

fix(collator): apply gas price factor to fee recovery threshold

---

collator/src/manager/blocks_cache.rs
collator/src/manager/mod.rs

What fixed:
* Node that collates normally may panic if it was excluded from validator set.
Backward compatible.

fix sync after excluding from vset

---

consensus/src/intercom/core/dispatcher.rs
consensus/src/intercom/core/dto.rs
consensus/src/intercom/core/responder.rs
consensus/src/intercom/dependency/downloader.rs
consensus/src/intercom/dto.rs
consensus/src/models/point/impl_.rs
consensus/src/proto.tl

Exposes `Point` deserialization and hash check, so they can be delegated to rayon. Also raw point bytes can be preserved until inserted into db.

refactor(consensus): simplify query wrapper

---

Cargo.lock
Cargo.toml
block-util/benches/common.rs
block-util/src/message/ext_msg_repr.rs
cli/src/cmd/elect/mod.rs
cli/src/cmd/tools/bc.rs
collator/src/collator/do_collate/prepare.rs
collator/tests/internal_queue.rs

- Adds support for `RUNVM`, `RUNVMX` and `GASCONSUMED` opcodes;
- Changes behaviour for extra currencies;
- Changes behaviour for some address rewrite opcodes;

feat(collator): update VM and executor to v10

---

collator/src/collator/messages_reader/externals_reader.rs
collator/src/collator/messages_reader/internals_reader.rs
collator/src/collator/messages_reader/mod.rs
collator/src/collator/mod.rs
collator/src/collator/tests/collator_tests.rs
collator/src/collator/tests/externals_reader_tests.rs
collator/src/mempool/impls/std_impl.rs
collator/src/mempool/impls/stub_impl.rs
collator/src/mempool/mod.rs

None
None
Message Processing Algorithm - fully compatible
Messages reading in ReFill mode little bit changes but this does not affect messages collection at all
Not Required
Expected impact
Little bit better overall performance of network because there are no endless syncs. But in it is not notable with existing tests. It is not the main goal.
**TESTS**
**Unit Tests**
Covered by: test_import_init_anchors, test_read_externals, test_refill_messages
**Network Tests**
No special coverage
**Manual Tests**
Any heavy test (swaps 1300, transfers 20k, 1-255) which causes many syncs. We should not have mismatched blocks in this case. …

reduce accumulated wu used on initial anchors import

---

collator/src/collator/do_collate/execute.rs
collator/src/collator/do_collate/mod.rs
collator/src/collator/execution_manager.rs
collator/src/collator/messages_reader/externals_reader.rs
collator/src/collator/messages_reader/internals_reader.rs
collator/src/collator/messages_reader/mod.rs
collator/src/collator/messages_reader/reader_state.rs
collator/src/collator/tests/externals_reader_tests.rs
collator/src/collator/types.rs
collator/src/internal_queue/gc.rs
collator/src/internal_queue/queue.rs

None
None
Message Processing Algorithm - fully compatible
Not Required
**TESTS**
**Unit Tests**
externals_reader_tests.rs, messages_reader_tests.rs
**Network Tests**
No special coverage
**Manual Tests**
To test this we run 1-255 and 10k transfers in parallel.
Before the fix node stucks after all messages in isolated partition 1 processed
[grafana](https://grafana.broxus.com/d/cdlaji62a1b0gb1/tycho-node-metrics-new-queue?orgId=1&from=2025-05-07T11:30:17.619Z&to=2025-05-07T12:14:24.532Z&timezone=browser&var-source=ced0ihciqrn5sb&var-instance=tycho-devnet2-validator1&var-instance=tycho-devnet2-validator2&var-instance=tycho-devnet2-valid …

fix next internals range reader creation

---

Cargo.lock
Cargo.toml
collator/src/collator/do_collate/finalize.rs
collator/src/collator/execution_manager.rs
collator/src/collator/types.rs
scripts/giver.py
scripts/init-zerostate-config.sh
scripts/libstore.py
scripts/requirements.txt
scripts/watch-elector.py

We are now able to introspect phases in executor, so a public libraries diff tracking can be significantly simplified. From the action phase we know about all new/removed libs and all that left to do is just to merge these changes.

feat(collator): simplify public libraries diff tracking

---

collator/src/collator/do_collate/execute.rs
collator/src/collator/do_collate/execution_wrapper.rs
collator/src/collator/do_collate/finalize.rs
collator/src/collator/do_collate/mod.rs
collator/src/collator/messages_buffer.rs
collator/src/collator/messages_reader/externals_reader.rs
collator/src/collator/messages_reader/internals_reader.rs
collator/src/collator/messages_reader/mod.rs
collator/src/collator/messages_reader/new_messages.rs
collator/src/collator/mod.rs
collator/src/collator/tests/externals_reader_tests.rs
collator/src/collator/tests/messages_buffer_tests.rs
collator/src/collator/tests/messages_reader_tests.rs
collator/src/collator/types.rs
scripts/gen-dashboard.py
util/src/cli/metrics.rs

None
None
Message Processing Algorithm - incompatible. Now we skip externals in buffer if they expired. So, if we have large externals queue on node update then refill may result into inconsistent queue state because before expired externals were always collected from buffer.
Required
* We need to perform deploy when workload is low and there is no externals queue. Otherwise updated node may skip external or execute it one more time.
* Needs to update the Grafana dashboard.
* Needs to set up the externals timeout
```
.params.28.msgs_exec_params.externals_expire_timeout = 58
```
Expected impact
Will reduce the "Fill messages" phase performance little …

do not mix externals above the vertical limit on account

---

.github/PULL_REQUEST_TEMPLATE.md
Cargo.lock
Cargo.toml
collator/src/collator/do_collate/execute.rs
collator/src/collator/do_collate/execution_wrapper.rs
collator/src/collator/do_collate/finalize.rs
collator/src/collator/do_collate/mod.rs
collator/src/collator/do_collate/prepare.rs
collator/src/collator/do_collate/work_units.rs
collator/src/collator/execution_manager.rs
collator/src/collator/messages_buffer.rs
collator/src/collator/mod.rs
collator/src/collator/types.rs
scripts/gen-dashboard.py

None
None
---
Affected features:
- State - special logic applied
- Collator. Work Units Calculation - special logic applied
Field `ShardStateUnsplit.underload_history` is used to track shard accounts count in state. After node update this field will be 0. In this case actual accounts count will be read from `ShardAccounts` dict only once. All next times it will be updated each block by added and removed accounts.
Compatibility was tested manually. Previous node version was deployed, then 20k accounts were deployed. After that nodes were updated to the latest version.
[metrics](https://grafana.broxus.com/d/cdlaji62a1b0gb1/tycho-node-metrics-high-times?orgId=1&from=2025-06-23T13:54:53.882Z&to=2025-06-23T14:24:50.879Z&timezone=browser&var-source=ced0ihciqrn5sb&var-instance=tycho-devnet2-valid …

detailed wu price

---

network/src/lib.rs
network/src/network/config.rs
network/src/network/mod.rs

Despite `Bbr` being experimental it behaves better than the default `Cubic`. We mostly use good 1gbit links for our networks and these are exactly the conditions for which `Bbr` is designed. 
Btw, even in the office network this algorithm behaves better than the default.
None
None
---
Fully compatible
Not Required
---
Expected impact: network will utilize channel resources better (at least for mempool).
---
Mostly mempool related when running too many nodes on too little servers. With `Bbr` algorithm they no longer fall out of sync.

feat(network): use `Bbr` as the default congestion control algorithm

---

core/src/blockchain_rpc/service.rs
scripts/gen-dashboard.py

Reduce boilerplate for metrics.
Split rpc on several files.

refactor(core): centralize `blockchain_rpc` methods into a single enum

---

consensus/src/dag/dag_point_future.rs
consensus/src/dag/dag_round.rs
consensus/src/dag/verifier.rs
network/src/dht/query.rs
util/src/futures/shared.rs
util/src/lib.rs

Point validation now uses weak references to its dependency points, while the single guaranteed strong ref is held by DagRound. So drop of DagRound will lead to drop of points as it is intended.
None
None
---
Full
Not Required
---
No impact expected in general. 
Nodes that fail to sync several times in a row may accomplish it faster. 
---
No coverage
No specific coverage, but every network test with mempool uses this change.
transfers-30k for 7 hours, simulator

fix(consensus): drop unresolved dag points with their rounds

---

cli/src/util/mod.rs
collator/src/collator/do_collate/finalize.rs
collator/src/collator/tests/messages_reader_tests.rs
core/src/storage/block/blobs/mod.rs
core/src/storage/persistent_state/queue_state/writer.rs
core/src/storage/persistent_state/shard_state/writer.rs
util/src/sync/task.rs
util/src/tl.rs

`cargo clippy --all --all-targets --fix`

chore: fix clippy errors for 1.90

---

Cargo.lock
Cargo.toml
core/src/storage/block/blobs/mod.rs

Db format is incompatible with prev one, but we have no release with prev version anyway.
Everything else is the same, except fixed logic errors in the db

fix(core): bump cassadilia version

---

collator/src/collator/do_collate/execute.rs
collator/src/collator/do_collate/execution_wrapper.rs
collator/src/collator/do_collate/mod.rs
collator/src/collator/execution_manager.rs
collator/src/collator/messages_buffer.rs
collator/src/collator/messages_reader/externals_reader.rs
collator/src/collator/messages_reader/internals_reader.rs
collator/src/collator/messages_reader/new_messages.rs
collator/src/collator/types.rs
collator/src/types.rs
scripts/gen-dashboard.py

None
None
Block may contain different data compared to old logic when the limit is reached. Nodes should be updated without load 
Nodes should be updated without load 
Required to define the appropriate limit and make changes in zerostate `22` and `23`
```{
"bytes": {
...
"hard_limit": 20000
},
"lt_delta": {
...
"hard_limit": 50000
}
}
```
The node stops producing blocks with a huge number of accounts
No coverage
- [transfers 20k master](https://grafana.broxus.com/d/cdlaji62a1b0gb/tycho-node-metrics?orgId=1&from=2025-09-10T10:51:53.566Z&to=2025-09-10T11:56:53.566Z&timezone=browser&var-source=ced0ihciqrn5sb&var-instance=tycho-devnet6-validator2&var-instance=tycho-devnet6-validator3&var-instance=tycho-devnet6-validator13&var-instance=tycho-devnet6-validator10&var-instance=tycho-devnet6-valid …

feature(collator): new block limits by items

---

core/src/storage/db.rs
core/src/storage/mod.rs
core/src/storage/persistent_state/mod.rs
core/src/storage/persistent_state/shard_state/writer.rs
core/src/storage/shard_state/cell_storage.rs
core/src/storage/shard_state/mod.rs
core/src/storage/shard_state/store_state_raw.rs

Using a separate db for cells reduces locking on the write path and eliminates most cases of tokio blocking.
Data obtained from running transfers 20k for 1h.
| name | tokio total block before | tokio total block after | diff_human |
|:-|:-|:-|:-|
| tycho_core::storage::block::store_block_data | 2 hours and 39 minutes | 58 seconds | 2 hours, 38 minutes and 2 seconds |
| tycho_collator::state_node::store_state_root | 2 hours, 1 minute and 20 seconds | 25 seconds | 2 hours and 55 seconds |
| tycho_core::block_strider::process_shard_blocks | 1 hour, 48 minutes and 43 seconds | 44 seconds | 1 hour, 47 minutes and 59 seconds |
| tycho_core::storage::block::store_block_proof | 40 minutes and 30 seconds | 27 seconds | 40 minutes and 3 seconds |
| …

Use separate rocksdb for cells 

---

Cargo.lock
block-util/Cargo.toml
block-util/src/state/min_ref_mc_state.rs
block-util/src/state/shard_state_stuff.rs
collator/src/collator/do_collate/finalize.rs
collator/src/collator/do_collate/mod.rs
collator/src/collator/mod.rs
collator/src/collator/tests/collator_tests.rs
collator/src/collator/types.rs
collator/src/manager/tests/manager_tests.rs
collator/src/state_node.rs
collator/src/test_utils.rs
collator/src/types.rs
collator/tests/adapter_tests.rs
collator/tests/collation_tests.rs
core/Cargo.toml
core/src/block_strider/starter/cold_boot.rs
core/src/block_strider/starter/mod.rs
core/src/block_strider/state_applier.rs
core/src/storage/persistent_state/mod.rs
core/src/storage/persistent_state/tests.rs
core/src/storage/shard_state/cell_storage.rs
core/src/storage/shard_state/mod.rs
core/src/storage/shard_state/store_state_raw.rs
core/tests/archives.rs
core/tests/overlay_server.rs
core/tests/utils/mod.rs
scripts/gen-dashboard.py
storage/Cargo.toml
storage/src/kv/refcount.rs

Yes
Added .collator. merkle_chain_limit: usize with default value 5.
None
---
Fully compatible
Not Required
---
Producing shard blocks improved: TPS increased by about 10-20%. Time diff reduced a bit but more nodes start to lag behind. The average resume collation time decreased significantly.
---
Yes
Deploy 10M accounts then run 20k transfers
(master is on the right) [grafana](https://grafana.broxus.com/d/cdlaji62a1b0gb/tycho-node-metrics?orgId=1&from=2025-08-29T13:36:23.903Z&to=2025-08-29T15:16:49.606Z&timezone=browser&var-source=ced0ihciqrn5sb&var-instance=tycho-devnet5-validator4&var-instance=tycho-devnet5-validator9&var-instance=tycho-devnet5-validator8&var-instance=tycho-devnet5-validator12&var-instance=tycho-devnet5-validator13&var-instance=tycho-devnet5-validator3&var-instance=tych …

feat(collator): don't wait state update

---

Cargo.lock
Cargo.toml

- Updated core dependencies and removed some transitive old ones;
- Switched back to published tycho crates.
NOTE: All tycho deps were bumped to 0.3 because the next release version will be kind of braking (0.2.x -> 0.3.0).

chore: bump quinn and tokio; remove old dependencies

---

block-util/src/message/ext_msg_repr.rs
core/src/block_strider/starter/cold_boot.rs
core/src/block_strider/starter/mod.rs
core/src/node/mod.rs
core/tests/overlay_server.rs
light-node/src/cli.rs

It adds useless complexity and is still insufficient this way.

fix(block-util): revert workchain range check for `ExtMsgRepr`

---

.github/workflows/ci.yml
contracts/src/elector-base.tolk
contracts/src/elector-poa.tolk
contracts/src/elector.tolk
contracts/tests/Elector.spec.ts

- Previously, when election failed, it was impossible to change anything after that because there was no flag reset in the stake handler.
- There were some unneeded `data` overwrites in the tick-tock handler. Without them contract behavior is closer to the original one, and the resulting code is smaller.

fix(contracts): properly reset election flags on each new stake
